repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: python3 -m black --config .black.toml
        language: system
        type: [python]
        files: '.*.py$'
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python3 -m pylint --rcfile .pylintrc
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]

